### ISSUE TITLE
[Bug] compilation of uYou's issues

### ISSUE THREAD

**Issue by qnblackcat** [MiRO92/uYou-for-YouTube#134]
It's good to know that you will start working on update uYou ❤️ I've summarized all the issues related to uYou from uYouPlus's repo here: https://github.com/qnblackcat/uYouPlus/labels/uYou. I hope it will help you improve uYou 😊

**Comment by theoccurrence** [comment]
You didn't list the two most frustrating bugs, which made me buy Cercube when uYou stopped being developed:

- When installing the app via AppDB there are permission errors that keep videos from being downloaded

- Download speed is excruciatingly slow (always has been) but it's slow even when using uYouLocal. It's slow to the point of almost being unusable (20-80 kb/s)

**Comment by qnblackcat** [comment]
> When installing the app via AppDB there are permission errors that keep videos from being downloaded.
You should use the Apple Development certificate when installing uYou from appdb. You should read the description before complaining. If it still doesn't work, then it’s probably an issue of appdb.

> Download speed is excruciatingly slow...
I believe MiRO92 had already awakened from this problem and he is working hard on it. Just let's the man do his job.

**Comment by theoccurrence** [comment]
> You should use the Apple Development certificate when installing uYou from appdb. You should read the description before complaining. If it still doesn't work, then it’s probably an issue of appdb.

Well, in case you're speaking of the identity type to use AppDB with, I am using "Development", yes. I am capable of reading descriptions. Also uYou 2.0 still works using this method, so you tell me wether it is a problem with appDB or uYou. I have no idea why appDB should work with 2.0 but not with 2.1, if it's an issue with appDB.

I also opened an issue when uYou 2.1 was released, where I go into more detail about this problem.

https://github.com/MiRO92/uYou-for-YouTube/issues/70

And concerning the slow download speed ... I don't want to pester anybody or keeping them from "doing their jobs", but this has been a problem for a long time, and I don't think that there's a fix without completely changing the download manager, that's why I suggested using yt-dlp instead. Miro definitely knows about this, because he closed or commented a couple of issues, where I mentioned this in the past.

**Comment by dayanch96** [comment]
> > You should use the Apple Development certificate when installing uYou from appdb. You should read the description before complaining. If it still doesn't work, then it’s probably an issue of appdb.
> 
> Well, in case you're speaking of the identity type to use AppDB with, I am using "Development", yes. I am capable of reading descriptions. Also uYou 2.0 still works using this method, so you tell me wether it is a problem with appDB or uYou. I have no idea why appDB should work with 2.0 but not with 2.1, if it's an issue with appDB. Besides, appDB is not even the only signing service that has this problem. Signolous and Esign show the same behavior. I would even go so far as to say that AltStore (for whatever reason) is the only signing service that doesn't have this problem.
> 
> I also opened an issue when uYou 2.1 was released, where I go into more detail about this problem.
> 
> #70
> 
> And concerning the slow download speed ... I don't want to pester anybody or keeping them from "doing their jobs", but this has been a problem for a long time, and I don't think that there's a fix without completely changing the download manager, that's why I suggested using yt-dlp instead. Miro definitely knows about this, because he closed or commented a couple of issues, where I mentioned this in the past.

Most probably its uYou issue. You can’t even install app if you’ll try enable FileSharing in YT’s info.plist. Looks like Sideloadly/AltStore changes something in app to access to Documents so it works fine.
