### ISSUE TITLE
Google won’t let me sign in 

### ISSUE THREAD

**Issue by EjinLives** [MiRO92/uYou-for-YouTube#154]
Every time I try to sign in it says it isn’t safe.

**Comment by hpopescu88** [comment]
Same issue

**Comment by martenmatrix** [comment]
This also happens with my account. However, I didn't change my phone recently and my Google account is some years old.

**Comment by Primemeow** [comment]
This is a known issue on all modified YouTube clients on iOS. It seems to be linked to the app’s bundle ID not being `com.google.ios.youtube`, as well as the account having had 2FA on at any point. The only known ways around it, other than using a different account, are to sign it using the aforementioned bundle ID, either through a paid developer account and Xcode, or SignTools. At least, that’s what I’ve gleaned from issue 319 on uYouPlus.

**Comment by Tecon** [comment]
I logged in successfully after trying this. (Youtube 17.15.1) [https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-you-cant-sign-in-to-this-app-because-google-cant-confirm-that-its-safe-warning-when-signing-in](https://github.com/qnblackcat/uYouPlus/wiki/FAQ#q-you-cant-sign-in-to-this-app-because-google-cant-confirm-that-its-safe-warning-when-signing-in)

**Comment by fadikamil** [comment]
I have sideloaded the latest version of uYou but i still can't sign in.
I tried the workaround and even in safari incognito mode i cant sign in if i copy the link and use it in safari as mentioned.
The workaround link says that the problem is fixed but im stil facing the same issue.

Any ideas guys?

**Comment by helil** [comment]
FWIW, the workaround worked for me in "private browsing" in Firefox for iOS

**Comment by fadik17** [comment]
> FWIW, the workaround worked for me in "private browsing" in Firefox for iOS

Doesn't work for me anyway I try.
Safari, Firefox not even chrome. All display the same message that uyou it displaying.

**Comment by fadik17** [comment]
> > FWIW, the workaround worked for me in "private browsing" in Firefox for iOS
> 
> Doesn't work for me anyway I try.
> Safari, Firefox not even chrome. All display the same message that uyou it displaying.


Btw, if I try to log in with a different account then it works without the need of safari workaround.

I tried disabling my 2fa but still same issue...
