### ISSUE TITLE
Fullscreen to the right not working after update to iOS 16.

### ISSUE THREAD

**Issue by jouzka** [MiRO92/uYou-for-YouTube#166]
It seems as if the option stopped working after enabling it in the “other settings” section, but it does work when using the dedicated button in the video player.

**Comment by arichorn** [comment]
The cause is either that uYou’s ipa uses an older version of YouTube and Google pushes out server side changes across the app

or your opinion about iOS 16 is correct. I’m not an expert here so i personally wouldn’t know. we do gotta tell MiRO about this and YT stopped supporting iOS 12 & 13 in the app.

**Comment by arichorn** [comment]
alright so we might have to tell MiRO92 about this, uYou deserves a good update
We gotta show these two to MiRO92 since I listed all of the bugs here #152 #164

**Comment by oomek** [comment]
Any chance to get this feature back? It stopped working after I've upgraded from iPhone 7 with IOS 15 to iPhone 14 with IOS16+
