### ISSUE TITLE
Unable to play videos fullscreen on ipad

### ISSUE THREAD

**Issue by hkaparwan** [MiRO92/uYou-for-YouTube#400]
Steps to reproduce
Open YouTube app
Play a video
Click the full screen icon at the bottom right side of video
Again, click the full screen collapse icon at the bottom right side of video

Expected result
Should collapse into a normal form

Actual result
All the functions available in the full screen mode over the video playing stopped working

**Comment by mannyd209** [comment]
I'm having the same problem on my iPad Pro 12.9 on iPadOS 17..3.1. The uYou version I'm running is the 3.0.3. version. Pretty much when I fullscreen a video then going back to the normal screen it just don't work and then nothing works but the video keeps playing. I have to foreclose the app and re start it to go to another video. This has happened since 3.0.2.

**Comment by abbaskabul** [comment]
Same problem here iPad Pro M1 iOS 16.4.1

**Comment by petermhyung** [comment]
Same problem here iPad Pro M2 iOS 17.3.1

**Comment by arichornlover** [comment]
I unfortunately have this problem aswell.

**Comment by Mehranullah2017** [comment]
Yes my YouTube app freezes on ipad if i try to exit full screen 
This bug only happens in landscape mode not in portrait mode

**Comment by axpmonkey** [comment]
This is happening in 3.0.2 and 3.0.3.  Just on the iPad in landscape mode. Mine is an M2 Pro, 17.3.1.  Haven’t seen this issue on an iPhone.

**Comment by hmu-duc-anh** [comment]
iPad Pro 12.9 2nd Gen, iOS 17.4.1. I have this exact error as well

**Comment by a1184375899** [comment]
I have this issue too, when exit full screen it just freeze, I tried so many versions it just don’t work
