### ISSUE TITLE
[Questions] Answers requested :)

### ISSUE THREAD

**Issue by Nexinity7** [MiRO92/uYou-for-YouTube#57]
1. What's the difference between the uYou and uYouLocal download buttons?
2. What does the uYouPiP button do? (I'll click it, select a quality and have nothing happen)
3. Videos after being clicked on will not play automatically (the play button must be pressed again), is there a way to change this?

EDIT: Forgot to mention that downloads stutter hard, is this normal behavior?

Otherwise, this tweak is awesome! i'll definitely be pushing this to everyone i know in the scene :)

**Comment by theoccurrence** [comment]
1. The uYouLocal button will take the link and download the audio/video directly to your device, without depending on any server. The normal uYou button depends on a server that Miro92 is providing. The file sizes may vary between the two methods, because uYouLocal downloads videos as mkv file and converts it to a MP4 file afterwards.

2. The uYouPiP button should turn the video you're watching into a picture in picture window. It doesn't seem to work in the newest update, at least for the sideloaded version. There are projects like uYou+ on AppDB, that also include other tweaks in a sideloadable IPA, with working PiP functionality.

3. Go into the uYou settings and look in "Other Settings" for the "Disable Video Auto Play" toggle and turn that off.

4. The downloads stuttering and generally not being fast, no matter your personal internet speed, is because of uYou relying on a server.

I found out, that constantly pausing and unpausing a download will give you short bursts of fast download speeds, speeding up the whole process a lot (if you're willing to hit that pause button for a hundred times).

I don't have an explanation, why the uYou local feature also suffers from the same slow download speeds though ... At least it can be sped up with the same technique.
