### ISSUE TITLE
Video Quality Does Not Exceed 1080p on iPhone 12

### ISSUE THREAD

**Issue by BionicBison05** [MiRO92/uYou-for-YouTube#77]
![1349FD8B-5597-4DA3-9A95-CF1A1764AA0E](https://user-images.githubusercontent.com/93722725/140335331-6575d47e-4ae4-4f83-b78f-eb3aca0ecec9.jpeg)

This video has a higher resolution than 1080p when viewed in the official YouTube app and on desktop, and it can be downloaded but not streamed by uYou in these higher resolutions. This is the sideloaded version of uYou.

**Comment by qnblackcat** [comment]
FYI, Apple allows YouTube to use a special **entitlement** called. 

> `com.apple.developer.coremedia.allow-alternate-video-decoder-selection`

Without this entitlement, you won't be able to use VP9 codec, which means no 2k/4k quality. 

It is impossible to keep that entitlement when sideloading because it's a private entitlement, no one except Google can use it. The entitlement is undocumented on Apple website. _Funny how Apple treats developers **equally** /s_

=> In short: no, nothing wrong with uYou. If you want 2k/4k quality, add **YTUHD** by Poomsmart alongside with uY
![Screen_Shot_2021-10-28_at_18 45 44](https://user-images.githubusercontent.com/52943116/140377751-fe3168f4-955d-404a-8454-10ae1ef07cbf.png)
ou

**Comment by BionicBison05** [comment]
Thanks for the tip, works like a charm. Sounds like something MiRO92 could add to uYou in the future though.

**Comment by ng4ever** [comment]
> 
> 
> Thanks for the tip, works like a charm. Sounds like something MiRO92 could add to uYou in the future though.

I agree!
